IF EXISTS (SELECT 1 FROM sys.databases WHERE name - 'DataWherehouse')
BEGIN
	ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE DateWarehouse;
END;

CREATE DATABASE DataWarehouse;

CREATE SCHEMA bronze;

CREATE SCHEMA silver;

CREATE SCHEMA gold;
